/**
 * AETHER — default seeded question bank (statement + options; images rendered at seed time).
 * 42 questions: aptitude 10 easy / 8 medium / 6 hard; technical 8 easy / 6 medium / 4 hard.
 * Seeding shuffles option order per question and recomputes the correct option, so
 * answer positions vary between databases.
 */

export interface SeedQuestion {
  id: string;
  roundType: 'aptitude' | 'technical';
  category: 'quantitative-aptitude' | 'logical-reasoning' | 'verbal-ability' | 'technical-quiz' | 'puzzle-solving';
  difficulty: 'easy' | 'medium' | 'hard';
  statement: string;
  options: [string, string, string, string];
  answer: string;
  explanation: string;
}

export const SEED_QUESTIONS: SeedQuestion[] = [
  // ── Aptitude · easy (10) ──────────────────────────────────────────────────
  { id: 'APT-E-01', roundType: 'aptitude', category: 'quantitative-aptitude', difficulty: 'easy',
    statement: 'A shopkeeper sells 15 notebooks at 4 rupees each. What is the total amount collected?',
    options: ['60 rupees', '45 rupees', '75 rupees', '55 rupees'], answer: '60 rupees',
    explanation: 'Total = 15 × 4 = 60 rupees.' },
  { id: 'APT-E-02', roundType: 'aptitude', category: 'quantitative-aptitude', difficulty: 'easy',
    statement: 'What is the value of 240 ÷ 8?',
    options: ['30', '24', '32', '28'], answer: '30',
    explanation: '8 × 30 = 240, so 240 ÷ 8 = 30.' },
  { id: 'APT-E-03', roundType: 'aptitude', category: 'quantitative-aptitude', difficulty: 'easy',
    statement: 'A student scored 25% marks out of 80 in a quiz. How many marks did the student get?',
    options: ['20', '25', '16', '24'], answer: '20',
    explanation: '25% of 80 = 80 × 1/4 = 20.' },
  { id: 'APT-E-04', roundType: 'aptitude', category: 'logical-reasoning', difficulty: 'easy',
    statement: 'Find the next number in the series: 2, 4, 6, 8, ...',
    options: ['10', '9', '12', '11'], answer: '10',
    explanation: 'The series increases by 2 each step, so the next number is 8 + 2 = 10.' },
  { id: 'APT-E-05', roundType: 'aptitude', category: 'logical-reasoning', difficulty: 'easy',
    statement: 'Find the next number in the series: 5, 10, 20, 40, ...',
    options: ['80', '60', '45', '90'], answer: '80',
    explanation: 'Each term doubles, so the next term is 40 × 2 = 80.' },
  { id: 'APT-E-06', roundType: 'aptitude', category: 'quantitative-aptitude', difficulty: 'easy',
    statement: 'What is the value of 4 squared minus 3 squared?',
    options: ['7', '1', '12', '5'], answer: '7',
    explanation: '4² = 16 and 3² = 9, so the difference is 16 − 9 = 7.' },
  { id: 'APT-E-07', roundType: 'aptitude', category: 'quantitative-aptitude', difficulty: 'easy',
    statement: 'What is the sum of 7, 8 and 9?',
    options: ['24', '21', '27', '25'], answer: '24',
    explanation: '7 + 8 + 9 = 24.' },
  { id: 'APT-E-08', roundType: 'aptitude', category: 'verbal-ability', difficulty: 'easy',
    statement: 'Complete the analogy: Cat is to Kitten as Dog is to ______.',
    options: ['Puppy', 'Calf', 'Cub', 'Foal'], answer: 'Puppy',
    explanation: 'A kitten is a young cat; likewise a puppy is a young dog.' },
  { id: 'APT-E-09', roundType: 'aptitude', category: 'quantitative-aptitude', difficulty: 'easy',
    statement: 'A meeting starts at 7:15 and lasts 45 minutes. When does it end?',
    options: ['8:00', '7:45', '8:15', '7:50'], answer: '8:00',
    explanation: '45 minutes after 7:15 is 8:00.' },
  { id: 'APT-E-10', roundType: 'aptitude', category: 'logical-reasoning', difficulty: 'easy',
    statement: 'Choose the number that does not belong: 3, 5, 7, 9, 11.',
    options: ['9', '3', '5', '11'], answer: '9',
    explanation: 'All listed numbers are prime except 9, which equals 3 × 3.' },

  // ── Aptitude · medium (8) ─────────────────────────────────────────────────
  { id: 'APT-M-01', roundType: 'aptitude', category: 'quantitative-aptitude', difficulty: 'medium',
    statement: 'A jacket priced at 450 rupees is sold at a 20% discount. What is the selling price?',
    options: ['360 rupees', '380 rupees', '400 rupees', '430 rupees'], answer: '360 rupees',
    explanation: 'Discount = 20% of 450 = 90, so the selling price is 450 − 90 = 360 rupees.' },
  { id: 'APT-M-02', roundType: 'aptitude', category: 'quantitative-aptitude', difficulty: 'medium',
    statement: 'What is the average of 12, 18, 24 and 30?',
    options: ['21', '20', '22', '24'], answer: '21',
    explanation: 'Sum = 84 and 84 ÷ 4 = 21.' },
  { id: 'APT-M-03', roundType: 'aptitude', category: 'logical-reasoning', difficulty: 'medium',
    statement: 'Find the missing term: 3, 6, 12, 24, ...',
    options: ['48', '36', '30', '42'], answer: '48',
    explanation: 'Each term is twice the previous term, so 24 × 2 = 48.' },
  { id: 'APT-M-04', roundType: 'aptitude', category: 'quantitative-aptitude', difficulty: 'medium',
    statement: 'A train runs at 60 km/h without stops. How long does it take to cover 90 km?',
    options: ['90 minutes', '60 minutes', '75 minutes', '100 minutes'], answer: '90 minutes',
    explanation: 'Time = 90 ÷ 60 = 1.5 hours = 90 minutes.' },
  { id: 'APT-M-05', roundType: 'aptitude', category: 'quantitative-aptitude', difficulty: 'medium',
    statement: 'Find the simple interest on 1000 rupees at 5% per year for 2 years.',
    options: ['100 rupees', '50 rupees', '150 rupees', '110 rupees'], answer: '100 rupees',
    explanation: 'SI = P × R × T / 100 = 1000 × 5 × 2 / 100 = 100 rupees.' },
  { id: 'APT-M-06', roundType: 'aptitude', category: 'quantitative-aptitude', difficulty: 'medium',
    statement: 'Two numbers are in the ratio 3 : 5 and their sum is 40. What is the smaller number?',
    options: ['15', '25', '12', '18'], answer: '15',
    explanation: 'Parts = 40 ÷ 8 = 5, so the numbers are 15 and 25; the smaller is 15.' },
  { id: 'APT-M-07', roundType: 'aptitude', category: 'logical-reasoning', difficulty: 'medium',
    statement: 'Which option continues the letter series: E, G, I, K, ...?',
    options: ['M', 'L', 'N', 'O'], answer: 'M',
    explanation: 'Each letter skips one position (E→G→I→K), so the next letter is M.' },
  { id: 'APT-M-08', roundType: 'aptitude', category: 'logical-reasoning', difficulty: 'medium',
    statement: 'If A=1, B=2, C=3 and so on, what is the code for the word CAB?',
    options: ['312', '123', '231', '321'], answer: '312',
    explanation: 'C=3, A=1, B=2, so CAB is coded as 312.' },

  // ── Aptitude · hard (6) ───────────────────────────────────────────────────
  { id: 'APT-H-01', roundType: 'aptitude', category: 'quantitative-aptitude', difficulty: 'hard',
    statement: 'A boat moves at 10 km/h in still water and the current runs at 2 km/h. How long to travel 12 km downstream?',
    options: ['1 hour', '1.5 hours', '1.2 hours', '2 hours'], answer: '1 hour',
    explanation: 'Downstream speed = 10 + 2 = 12 km/h, so time = 12 ÷ 12 = 1 hour.' },
  { id: 'APT-H-02', roundType: 'aptitude', category: 'quantitative-aptitude', difficulty: 'hard',
    statement: 'Pipe A fills a tank in 6 hours and pipe B fills it in 12 hours. How long do both take together?',
    options: ['4 hours', '3 hours', '5 hours', '9 hours'], answer: '4 hours',
    explanation: 'Combined rate = 1/6 + 1/12 = 1/4 tank per hour, so 4 hours.' },
  { id: 'APT-H-03', roundType: 'aptitude', category: 'logical-reasoning', difficulty: 'hard',
    statement: 'Ravi is three times as old as his son. In 12 years Ravi will be twice as old as his son. What is Ravi\u2019s current age?',
    options: ['36 years', '30 years', '42 years', '33 years'], answer: '36 years',
    explanation: 'Let the son be S: 3S + 12 = 2(S + 12) gives S = 12, so Ravi is 36.' },
  { id: 'APT-H-04', roundType: 'aptitude', category: 'quantitative-aptitude', difficulty: 'hard',
    statement: 'Find the compound interest on 5000 rupees at 10% per year for 2 years, compounded yearly.',
    options: ['550 rupees', '500 rupees', '605 rupees', '520 rupees'], answer: '550 rupees',
    explanation: 'Amount = 5000 × 1.1² = 6050, so the interest is 6050 − 5000 = 550 rupees.' },
  { id: 'APT-H-05', roundType: 'aptitude', category: 'puzzle-solving', difficulty: 'hard',
    statement: 'On a standard die, opposite faces add up to 7. If the top face shows 1, which number is on the bottom?',
    options: ['6', '5', '4', '3'], answer: '6',
    explanation: 'Opposite faces sum to 7, so the face opposite 1 is 6.' },
  { id: 'APT-H-06', roundType: 'aptitude', category: 'logical-reasoning', difficulty: 'hard',
    statement: 'In a race, A finished before B but after C, and D finished before C. Who won the race?',
    options: ['D', 'A', 'B', 'C'], answer: 'D',
    explanation: 'Order from fastest: D, C, A, B — so D finished first.' },

  // ── Technical · easy (8) ──────────────────────────────────────────────────
  { id: 'TEC-E-01', roundType: 'technical', category: 'technical-quiz', difficulty: 'easy',
    statement: 'In almost all modern programming languages, what is the index of the first element of an array?',
    options: ['0', '1', '-1', 'It depends on the array size'], answer: '0',
    explanation: 'Arrays are zero-indexed in languages such as C, Java, Python and JavaScript.' },
  { id: 'TEC-E-02', roundType: 'technical', category: 'technical-quiz', difficulty: 'easy',
    statement: 'What is the average time complexity of binary search on a sorted array?',
    options: ['O(log n)', 'O(n)', 'O(n log n)', 'O(1)'], answer: 'O(log n)',
    explanation: 'Binary search halves the search space each step, giving logarithmic time.' },
  { id: 'TEC-E-03', roundType: 'technical', category: 'technical-quiz', difficulty: 'easy',
    statement: 'In web development, what does CSS stand for?',
    options: ['Cascading Style Sheets', 'Computer Styled Sections', 'Creative Style System', 'Coded Style Syntax'], answer: 'Cascading Style Sheets',
    explanation: 'CSS stands for Cascading Style Sheets.' },
  { id: 'TEC-E-04', roundType: 'technical', category: 'technical-quiz', difficulty: 'easy',
    statement: 'Which SQL statement retrieves rows from a database table?',
    options: ['SELECT', 'UPDATE', 'INSERT', 'DROP'], answer: 'SELECT',
    explanation: 'The SELECT statement queries and returns rows from a table.' },
  { id: 'TEC-E-05', roundType: 'technical', category: 'technical-quiz', difficulty: 'easy',
    statement: 'What does HTML stand for?',
    options: ['HyperText Markup Language', 'HighText Machine Language', 'Hyperlink Text Management Language', 'Home Tool Markup Language'], answer: 'HyperText Markup Language',
    explanation: 'HTML stands for HyperText Markup Language.' },
  { id: 'TEC-E-06', roundType: 'technical', category: 'technical-quiz', difficulty: 'easy',
    statement: 'Which data structure processes elements in Last-In-First-Out order?',
    options: ['Stack', 'Queue', 'Linked list', 'Binary tree'], answer: 'Stack',
    explanation: 'A stack pushes and pops from the same end, giving LIFO order.' },
  { id: 'TEC-E-07', roundType: 'technical', category: 'technical-quiz', difficulty: 'easy',
    statement: 'An HTTP response returns status code 404. What does it indicate?',
    options: ['Resource not found', 'Server error', 'Access forbidden', 'Request succeeded'], answer: 'Resource not found',
    explanation: '404 means the requested resource could not be found on the server.' },
  { id: 'TEC-E-08', roundType: 'technical', category: 'technical-quiz', difficulty: 'easy',
    statement: 'Which Git command creates a local copy of a remote repository?',
    options: ['git clone', 'git push', 'git merge', 'git commit'], answer: 'git clone',
    explanation: 'git clone downloads a repository with its full history.' },

  // ── Technical · medium (6) ────────────────────────────────────────────────
  { id: 'TEC-M-01', roundType: 'technical', category: 'technical-quiz', difficulty: 'medium',
    statement: 'An in-order traversal of a binary search tree visits the nodes in which order?',
    options: ['Sorted ascending order', 'Random order', 'Reverse sorted order', 'Level by level'], answer: 'Sorted ascending order',
    explanation: 'In-order traversal (left, node, right) of a BST yields keys in ascending order.' },
  { id: 'TEC-M-02', roundType: 'technical', category: 'technical-quiz', difficulty: 'medium',
    statement: 'Which property is guaranteed by a SQL PRIMARY KEY column?',
    options: ['Unique values and no nulls', 'Unique values but nulls allowed', 'Sorted storage order', 'Indexed but may repeat'], answer: 'Unique values and no nulls',
    explanation: 'A primary key uniquely identifies each row and cannot contain NULL.' },
  { id: 'TEC-M-03', roundType: 'technical', category: 'technical-quiz', difficulty: 'medium',
    statement: 'Which SQL join returns only rows that have matching values in both tables?',
    options: ['INNER JOIN', 'LEFT JOIN', 'FULL OUTER JOIN', 'CROSS JOIN'], answer: 'INNER JOIN',
    explanation: 'An INNER JOIN keeps only rows with matches in both tables.' },
  { id: 'TEC-M-04', roundType: 'technical', category: 'technical-quiz', difficulty: 'medium',
    statement: 'In JavaScript, which of the following is a complete set of possible Promise states?',
    options: ['Pending, fulfilled, rejected', 'Open, closed, failed', 'Queued, running, done', 'Start, wait, stop'], answer: 'Pending, fulfilled, rejected',
    explanation: 'A Promise is pending first and then settles as fulfilled or rejected.' },
  { id: 'TEC-M-05', roundType: 'technical', category: 'technical-quiz', difficulty: 'medium',
    statement: 'Dijkstra\u2019s shortest-path algorithm produces correct results only when which condition holds?',
    options: ['All edge weights are non-negative', 'The graph is a tree', 'The graph is directed', 'All vertices have equal degree'], answer: 'All edge weights are non-negative',
    explanation: 'Negative weights can break Dijkstra\u2019s greedy choice; Bellman-Ford handles them.' },
  { id: 'TEC-M-06', roundType: 'technical', category: 'technical-quiz', difficulty: 'medium',
    statement: 'Which data structure gives average O(1) time for lookups by key?',
    options: ['Hash table', 'Balanced binary search tree', 'Sorted array', 'Min-heap'], answer: 'Hash table',
    explanation: 'Hashing maps a key directly to a bucket, giving average constant-time lookup.' },

  // ── Technical · hard (4) ──────────────────────────────────────────────────
  { id: 'TEC-H-01', roundType: 'technical', category: 'technical-quiz', difficulty: 'hard',
    statement: 'Appending to a dynamic array occasionally triggers a resize, yet it is called amortized O(1). Why?',
    options: ['Resize cost spread over many appends averages out to constant', 'Resizing never actually copies elements', 'The compiler removes resize operations', 'Dynamic arrays store data in constant memory'], answer: 'Resize cost spread over many appends averages out to constant',
    explanation: 'Doubling capacity makes the total copy cost across n appends O(n), so each append is O(1) amortized.' },
  { id: 'TEC-H-02', roundType: 'technical', category: 'technical-quiz', difficulty: 'hard',
    statement: 'In SQL, what does the HAVING clause do?',
    options: ['Filters grouped rows after GROUP BY using aggregates', 'Filters single rows before grouping', 'Sorts the final result set', 'Creates a new grouped table'], answer: 'Filters grouped rows after GROUP BY using aggregates',
    explanation: 'WHERE filters rows before grouping; HAVING filters the aggregated groups afterwards.' },
  { id: 'TEC-H-03', roundType: 'technical', category: 'technical-quiz', difficulty: 'hard',
    statement: 'Which set of conditions together makes a deadlock possible?',
    options: ['Mutual exclusion, hold and wait, no preemption, circular wait', 'Preemption, paging, segmentation, swapping', 'Serialization, indexing, hashing, caching', 'Mutual exclusion, batching, spooling, buffering'], answer: 'Mutual exclusion, hold and wait, no preemption, circular wait',
    explanation: 'These are the four classic Coffman conditions; all must hold for a deadlock.' },
  { id: 'TEC-H-04', roundType: 'technical', category: 'technical-quiz', difficulty: 'hard',
    statement: 'Which feature primarily distinguishes TCP from UDP?',
    options: ['TCP is connection-oriented with ordered, reliable delivery', 'TCP is faster because it sends no acknowledgments', 'TCP is connectionless and best for live video', 'TCP only works on local networks'], answer: 'TCP is connection-oriented with ordered, reliable delivery',
    explanation: 'TCP establishes a connection and guarantees ordered delivery; UDP is connectionless and unreliable.' },
  { id: 'TEC-H-05', roundType: 'technical', category: 'technical-quiz', difficulty: 'hard',
    statement: 'Under the SQL standard, which isolation level prevents dirty reads but still permits phantom reads?',
    options: ['Read Committed', 'Serializable', 'Read Uncommitted', 'Repeatable Read'], answer: 'Read Committed',
    explanation: 'Read Committed only reads committed data (no dirty reads) but new rows can appear between queries; Serializable prevents phantoms.' },
];
