import { useCallback, useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import {
  FileText, Download, Loader2, ArrowLeft, Briefcase, Target, CheckCircle2, Sparkles,
} from 'lucide-react';
import toast from 'react-hot-toast';
import { Button } from '../components/ui/button';
import { Card } from '../components/ui/card';
import {
  builderService, type IAtsResult, type IJdMatch, type IVersionSummary,
} from '../services/resumeBuilderService';
import {
  emptyResume, normalizeResume, TEMPLATES, type ResumeDocument, type TemplateId,
} from '../features/resume/types';
import ResumeToolbar, { type SaveStatus } from '../features/resume/ResumeToolbar';
import PdfPreview, { AtsPanel } from '../features/resume/PdfPreview';
import { downloadResumePdf } from '../features/resume/pdf/exportPdf';
import {
  PersonalSection, SummarySection, ExperienceSection, ProjectsSection,
  EducationSection, SkillsCertificationsSection, LanguagesSection,
  CustomSectionsEditor, LayoutSection,
} from '../features/resume/ResumeEditor';

/**
 * AETHER Resume Builder (spec §14–§27).
 *
 * LEFT: structured section editor with repeatable entries.
 * RIGHT: live text-based PDF preview + deterministic ATS feedback.
 *
 * Autosave (debounced) persists to the backend; the ATS score is recomputed
 * server-side from the saved content — never generated by AI (spec §27).
 */
export default function ResumeBuilderPage() {
  const [versions, setVersions] = useState<IVersionSummary[]>([]);
  const [activeId, setActiveId] = useState<string | null>(null);
  const [versionName, setVersionName] = useState('My Resume');
  const [template, setTemplate] = useState<TemplateId>('ats-classic');
  const [doc, setDoc] = useState<ResumeDocument>(emptyResume());
  const [jd, setJd] = useState('');
  const [ats, setAts] = useState<IAtsResult | null>(null);
  const [jdMatch, setJdMatch] = useState<IJdMatch | null>(null);
  const [analyzing, setAnalyzing] = useState(false);
  const [status, setStatus] = useState<SaveStatus>('idle');
  const [lastSavedAt, setLastSavedAt] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState(false);
  const [previewKey, setPreviewKey] = useState(0);

  // Autosave needs the latest values without re-triggering on every keystroke.
  const stateRef = useRef({ doc, versionName, template, jd, activeId });
  stateRef.current = { doc, versionName, template, jd, activeId };
  const saveTimer = useRef<number | null>(null);
  const dirtyRef = useRef(false);

  // ── Initial load: default version first, else the newest one ───────────────
  useEffect(() => {
    let cancelled = false;
    builderService.listVersions()
      .then(list => {
        if (cancelled) return;
        setVersions(list);
        const initial = list.find(v => v.isDefault) || list[0];
        if (initial) applyVersion(initial);
      })
      .catch(() => { /* an empty account simply starts a new resume */ })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  const applyVersion = (v: IVersionSummary) => {
    const next = normalizeResume(v.data as unknown as Partial<ResumeDocument>);
    setActiveId(v._id);
    setVersionName(v.name);
    setTemplate((v.template as TemplateId) || 'ats-classic');
    setDoc(next);
    setJd(next.targetJobDescription || '');
    if (v.atsScore != null) {
      // Score is known; the detailed categories refresh from /ats/analyze.
      setAts(prev => prev);
    }
    setStatus('idle');
    dirtyRef.current = false;
    setPreviewKey(k => k + 1);
  };

  const patch = useCallback((fields: Partial<ResumeDocument>) => {
    setDoc(prev => ({ ...prev, ...fields }));
    dirtyRef.current = true;
    setStatus('dirty');
  }, []);

  // ── Autosave + ATS recompute (debounced, spec §25) ─────────────────────────
  useEffect(() => {
    if (!dirtyRef.current) return;
    const timer = window.setTimeout(async () => {
      const snap = stateRef.current;
      setStatus('saving');
      try {
        const payload = { ...snap.doc, targetJobDescription: snap.jd };
        if (snap.activeId) {
          const res = await builderService.updateVersion(snap.activeId, {
            name: snap.versionName, data: payload, template: snap.template,
          });
          if (res?.ats) setAts(res.ats);
        } else {
          const created = await builderService.createVersion({
            name: snap.versionName, data: payload, template: snap.template,
          });
          setActiveId(created._id);
          setVersions(prev => [created, ...prev]);
        }
        const list = await builderService.listVersions();
        setVersions(list);
        dirtyRef.current = false;
        setStatus('saved');
        setLastSavedAt(new Date().toLocaleTimeString());
      } catch (err: any) {
        setStatus('error');
        if (err?.message && /UPGRADE|plan allows/i.test(err.message)) toast.error(err.message);
      }
    }, 1100);
    if (saveTimer.current) window.clearTimeout(saveTimer.current);
    saveTimer.current = timer;
    return () => window.clearTimeout(timer);
  }, [doc, versionName, template, jd]);

  // ── Live deterministic ATS analysis (debounced, separate from saving) ──────
  useEffect(() => {
    const emptyish = !doc.name && !doc.summary && doc.experience.length === 0 && doc.projects.length === 0;
    if (emptyish) { setAts(null); setJdMatch(null); return; }
    const timer = window.setTimeout(async () => {
      setAnalyzing(true);
      try {
        const res = await builderService.analyze({ ...doc, targetJobDescription: jd } as any, jd || undefined);
        setAts(res.ats);
        setJdMatch(res.jdMatch);
      } catch {
        /* keep the last good score; the panel shows the previous value */
      } finally {
        setAnalyzing(false);
      }
    }, 1400);
    return () => window.clearTimeout(timer);
  }, [doc, jd]);

  const recompute = async () => {
    setAnalyzing(true);
    try {
      const res = await builderService.analyze({ ...doc, targetJobDescription: jd } as any, jd || undefined);
      setAts(res.ats);
      setJdMatch(res.jdMatch);
    } catch (e: any) {
      toast.error(e?.message || 'Could not compute the ATS score');
    } finally {
      setAnalyzing(false);
    }
  };

  // ── Version actions (spec §26) ─────────────────────────────────────────────
  const createVersion = () => {
    setActiveId(null);
    setVersionName(`Resume ${versions.length + 1}`);
    setDoc(emptyResume());
    setJd('');
    setAts(null);
    setJdMatch(null);
    setStatus('unsaved-new');
    setPreviewKey(k => k + 1);
    toast.success('New version started — it saves as soon as you type.');
  };

  const duplicateVersion = async (v: IVersionSummary) => {
    try {
      const copy = await builderService.createVersion({
        name: `${v.name} (copy)`,
        data: normalizeResume(v.data as unknown as Partial<ResumeDocument>),
        template: (v.template as TemplateId) || 'ats-classic',
      });
      const list = await builderService.listVersions();
      setVersions(list);
      applyVersion(copy);
      toast.success('Version duplicated');
    } catch (e: any) {
      toast.error(e?.message || 'Could not duplicate — plan limit reached?');
    }
  };

  const renameVersion = async (v: IVersionSummary, name: string) => {
    try {
      await builderService.updateVersion(v._id, {
        name,
        data: normalizeResume(v.data as unknown as Partial<ResumeDocument>),
        template: v.template,
      });
      if (v._id === activeId) setVersionName(name);
      const list = await builderService.listVersions();
      setVersions(list);
      toast.success('Renamed');
    } catch (e: any) {
      toast.error(e?.message || 'Rename failed');
    }
  };

  const setDefaultVersion = async (v: IVersionSummary) => {
    try {
      await builderService.setDefaultVersion(v._id);
      const list = await builderService.listVersions();
      setVersions(list);
      toast.success(`“${v.name}” is now your default version`);
    } catch (e: any) {
      toast.error(e?.message || 'Could not set default');
    }
  };

  const deleteVersion = async (v: IVersionSummary) => {
    if (!window.confirm(`Delete “${v.name}”? This cannot be undone.`)) return;
    try {
      await builderService.deleteVersion(v._id);
      const list = await builderService.listVersions();
      setVersions(list);
      if (v._id === activeId) {
        const next = list.find(x => x.isDefault) || list[0];
        if (next) applyVersion(next);
        else { setActiveId(null); setDoc(emptyResume()); setAts(null); }
      }
      toast.success('Version deleted');
    } catch (e: any) {
      toast.error(e?.message || 'Delete failed');
    }
  };

  const fromUploaded = async () => {
    try {
      const v = await builderService.createFromUpload({});
      const list = await builderService.listVersions();
      setVersions(list);
      applyVersion(v);
      toast.success('Version created from your latest uploaded resume');
    } catch (e: any) {
      toast.error(e?.message || 'No uploaded resume found — upload one in the Resume Analyzer first.');
    }
  };

  // ── PDF download (spec §22) ────────────────────────────────────────────────
  const download = async () => {
    setDownloading(true);
    const toastId = toast.loading('Preparing PDF…');
    try {
      const finalDoc = { ...doc, targetJobDescription: jd };
      toast.loading('Generating…', { id: toastId });
      const result = await downloadResumePdf(finalDoc, template);
      toast.success(`Downloaded ${result.filename}`, { id: toastId });
    } catch (e: any) {
      toast.error(e?.message || 'PDF generation failed', { id: toastId });
    } finally {
      setDownloading(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-background pt-20 px-6">
        <div className="mx-auto max-w-7xl flex items-center gap-2 text-sm text-muted-foreground">
          <Loader2 className="w-4 h-4 animate-spin" /> Loading your resume versions…
        </div>
      </div>
    );
  }

  const activeTemplate = TEMPLATES.find(t => t.id === template) || TEMPLATES[0];

  return (
    <div className="min-h-screen bg-background text-foreground px-4 sm:px-6 lg:px-8 pt-20 pb-14">
      <div className="mx-auto max-w-7xl space-y-4">
        {/* Header / toolbar (spec §14) */}
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-3">
          <div>
            <Link to="/resume-analyzer" className="text-xs text-muted-foreground hover:text-foreground inline-flex items-center gap-1 mb-1">
              <ArrowLeft className="w-3.5 h-3.5" /> Resume Analyzer
            </Link>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-semibold bg-primary/10 text-primary mb-1 ml-2">
              <FileText className="w-3.5 h-3.5" /> Resume Builder
            </div>
            <h1 className="text-2xl font-extrabold tracking-tight">Build an ATS-friendly resume</h1>
            <p className="text-[12.5px] text-muted-foreground mt-0.5">
              Structured sections on the left, a real text PDF on the right. Export and re-upload to the analyzer to verify parsing.
            </p>
          </div>
          <div className="flex flex-wrap items-center gap-2">
            <Button size="sm" variant="outline" onClick={() => setPreviewKey(k => k + 1)} className="text-xs">Refresh preview</Button>
            <Button size="sm" onClick={download} disabled={downloading} className="text-xs font-bold">
              {downloading ? <Loader2 className="w-3.5 h-3.5 mr-1.5 animate-spin" /> : <Download className="w-3.5 h-3.5 mr-1.5" />}
              Download PDF
            </Button>
          </div>
        </div>

        <Card className="p-4 rounded-2xl">
          <ResumeToolbar
            versions={versions}
            activeId={activeId}
            onSelect={applyVersion}
            onCreate={createVersion}
            onDuplicate={duplicateVersion}
            onDelete={deleteVersion}
            onRename={renameVersion}
            onSetDefault={setDefaultVersion}
            onFromUpload={fromUploaded}
            status={status}
            lastSavedAt={lastSavedAt}
          />
        </Card>

        <div className="grid lg:grid-cols-2 gap-5 items-start">
          {/* ── LEFT: editor ── */}
          <div className="space-y-3">
            <Card className="p-4 rounded-2xl space-y-2">
              <span className="block text-[10.5px] font-bold uppercase tracking-wider text-muted-foreground">Version name</span>
              <input
                className="w-full rounded-lg border border-border bg-background px-2.5 py-1.5 text-[13px] focus:outline-none focus:ring-2 focus:ring-ring"
                value={versionName}
                onChange={e => { setVersionName(e.target.value); dirtyRef.current = true; setStatus('dirty'); }}
                placeholder="Backend Developer — July 2026"
              />
              <p className="text-[11px] text-muted-foreground">
                Keep one version per target role (General, Backend, Data Analyst, company-specific).
              </p>
            </Card>

            <PersonalSection doc={doc} patch={patch} />
            <SummarySection doc={doc} patch={patch} />
            <ExperienceSection doc={doc} patch={patch} />
            <ProjectsSection doc={doc} patch={patch} />
            <EducationSection doc={doc} patch={patch} />
            <SkillsCertificationsSection doc={doc} patch={patch} />
            <LanguagesSection doc={doc} patch={patch} />
            <CustomSectionsEditor doc={doc} patch={patch} />

            {/* Template picker (spec §19) */}
            <Card className="p-4 rounded-2xl space-y-3">
              <p className="text-sm font-bold text-foreground inline-flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-primary" /> Template
              </p>
              <div className="grid sm:grid-cols-2 gap-2">
                {TEMPLATES.map(t => (
                  <button key={t.id} type="button" onClick={() => { setTemplate(t.id); dirtyRef.current = true; setStatus('dirty'); }}
                    className={`text-left rounded-xl border p-3 transition-colors ${template === t.id ? 'border-primary bg-primary/5' : 'border-border bg-card hover:border-primary/40'}`}>
                    <p className="text-[13px] font-semibold text-foreground flex items-center gap-1.5">
                      {t.label}
                      {t.recommended && (
                        <span className="text-[9.5px] font-bold px-1.5 py-0.5 rounded-full bg-emerald-50 text-emerald-700 border border-emerald-200 inline-flex items-center gap-0.5">
                          <CheckCircle2 className="w-2.5 h-2.5" /> RECOMMENDED
                        </span>
                      )}
                    </p>
                    <p className="text-[11px] text-muted-foreground mt-0.5">{t.desc}</p>
                  </button>
                ))}
              </div>
            </Card>

            <LayoutSection doc={doc} patch={patch} />

            <Card className="p-4 rounded-2xl space-y-2">
              <p className="text-sm font-bold text-foreground inline-flex items-center gap-2">
                <Target className="w-4 h-4 text-primary" /> Target job description
              </p>
              <textarea rows={6} className="w-full rounded-lg border border-border bg-background px-2.5 py-2 text-[12.5px] focus:outline-none focus:ring-2 focus:ring-ring"
                value={jd} onChange={e => { setJd(e.target.value); dirtyRef.current = true; setStatus('dirty'); }}
                placeholder="Paste the job posting here to see keyword alignment. Only add a missing keyword if you genuinely have that skill." />
            </Card>
          </div>

          {/* ── RIGHT: preview + ATS ── */}
          <div className="space-y-4 lg:sticky lg:top-20">
            <PdfPreview doc={{ ...doc, targetJobDescription: jd }} template={template} refreshKey={previewKey} />
            <div className="flex items-center justify-between gap-2 px-1">
              <span className="text-[11px] text-muted-foreground inline-flex items-center gap-1.5">
                <Briefcase className="w-3.5 h-3.5" /> {activeTemplate.label}
              </span>
              <Link to="/resume-analyzer" className="text-[11px] font-semibold text-primary hover:underline">
                Verify in Resume Analyzer →
              </Link>
            </div>
            <AtsPanel ats={ats} jdMatch={jdMatch} analyzing={analyzing} onRefresh={recompute} />
          </div>
        </div>
      </div>
    </div>
  );
}
