/**
 * AETHER Coding — Execution Trace types.
 *
 * Traces are REAL events emitted by an instrumented runtime (Python/JS) or a
 * compiled-language adapter (Java via bytecode/lineno-like adapter). They are
 * NEVER generated by AI. Gemini may only narrate a trace afterwards.
 *
 * Safety contract (enforced by the trace service):
 *  - maxTraceSteps   (default 2000) — infinite loops terminate safely
 *  - maxTraceBytes   (default 512KB serialized payload)
 *  - wall-clock timeout on the underlying runtime
 *  - collection snapshots are size-capped to avoid browser crashes
 */

export type TraceEventType =
  | 'LINE'
  | 'FUNCTION_CALL'
  | 'FUNCTION_RETURN'
  | 'VARIABLE_UPDATE'
  | 'CONDITION'
  | 'LOOP_ITERATION'
  | 'ARRAY_UPDATE'
  | 'MAP_UPDATE'
  | 'SET_UPDATE'
  | 'STACK_PUSH'
  | 'STACK_POP'
  | 'QUEUE_ENQUEUE'
  | 'QUEUE_DEQUEUE'
  | 'RECURSION_CALL'
  | 'OUTPUT';

/** A single normalized trace event (Section 6 of the spec). */
export interface ITraceEvent {
  /** 1-based step index */
  step: number;
  /** 1-based source line of the event (best effort; 0 when unavailable) */
  line: number;
  event: TraceEventType;
  /** enclosing function name ('<module>' for top level) */
  function: string;
  /** scalar/short variables at this step (capped) */
  variables?: Record<string, unknown>;
  /** named collection snapshots (arrays, maps, sets, stacks, queues…) */
  collections?: Record<string, unknown>;
  /** stdout accumulated up to this step (delta since last event is fine) */
  stdout?: string;
  /** call depth (0 = top-level) */
  callDepth: number;
  /** call stack frame labels, outermost first, current last */
  callStack?: string[];
  /** optional human note, e.g. "target 9 not found — store 2 → 0" */
  note?: string;
}

/** Heuristic algorithm-pattern annotation derived deterministically from the trace. */
export interface ITracePattern {
  pattern:
    | 'ARRAY_SCAN'
    | 'TWO_POINTER'
    | 'BINARY_SEARCH'
    | 'SLIDING_WINDOW'
    | 'SORTING'
    | 'HASHING'
    | 'STACK'
    | 'QUEUE'
    | 'RECURSION'
    | 'DP_TABLE'
    | 'DFS_BFS'
    | 'NESTED_LOOP';
  /** e.g. pointer variable names for two-pointer, "low,mid,high" for binary search */
  variables?: string[];
}

export interface ITraceMetadata {
  language: string;
  functionName?: string;
  /** the exact input that was traced — ALWAYS a sample/custom input, never hidden */
  inputPreview: string;
  totalSteps: number;
  truncated: boolean;
  finalOutput: string;
  /** wall time of the traced run in ms */
  runtimeMs: number;
  /** detected patterns (deterministic post-pass) */
  patterns: ITracePattern[];
  /** final return value serialization when captured */
  returnValue?: string;
  /** runtime error message when the traced run failed mid-execution (§41) —
   *  the visualizer keeps prior steps viewable and shows the failure state. */
  runtimeError?: string;
  /** engine that produced the trace */
  engine: 'python-instrumented' | 'js-instrumented' | 'java-adapter' | 'none';
}

export interface ITraceResult {
  ok: boolean;
  supported: boolean;
  reason?: string;
  events: ITraceEvent[];
  metadata: ITraceMetadata;
}

/** Limits (all server-side, env-overridable). */
export const TRACE_LIMITS = {
  maxTraceSteps: Number(process.env.TRACE_MAX_STEPS || 2000),
  maxTraceBytes: Number(process.env.TRACE_MAX_BYTES || 512 * 1024),
  maxVarCount: 24,
  maxVarValueLen: 120,
  maxCollectionEntries: 64,
  maxCollectionKeyLen: 40,
  maxEventsArrayBytes: 480 * 1024,
  runtimeTimeoutMs: Number(process.env.TRACE_TIMEOUT_MS || 15000),
} as const;

/** Serialize a value safely for the browser (bounded). */
export function safeSerialize(value: unknown): unknown {
  const seen = new WeakSet<object>();
  const walk = (v: unknown, depth: number): unknown => {
    if (v === null || v === undefined) return v === undefined ? null : v;
    const t = typeof v;
    if (t === 'number' || t === 'boolean') return v;
    if (t === 'string') {
      const s = v as string;
      return s.length > TRACE_LIMITS.maxVarValueLen ? s.slice(0, TRACE_LIMITS.maxVarValueLen) + '…' : s;
    }
    if (t === 'bigint') return String(v) + 'n';
    if (t === 'function' || t === 'symbol') return `<${t}>`;
    if (depth > 4) return '…';
    if (typeof v === 'object') {
      if (seen.has(v as object)) return '[Circular]';
      seen.add(v as object);
      if (Array.isArray(v)) {
        const arr = v.slice(0, TRACE_LIMITS.maxCollectionEntries).map(x => walk(x, depth + 1));
        if (v.length > TRACE_LIMITS.maxCollectionEntries) arr.push(`…(+${v.length - TRACE_LIMITS.maxCollectionEntries})`);
        return arr;
      }
      const out: Record<string, unknown> = {};
      let i = 0;
      for (const [k, val] of Object.entries(v as Record<string, unknown>)) {
        if (i++ >= TRACE_LIMITS.maxCollectionEntries) { out['…'] = `(+more)`; break; }
        out[String(k).slice(0, TRACE_LIMITS.maxCollectionKeyLen)] = walk(val, depth + 1);
      }
      return out;
    }
    return String(v);
  };
  try { return walk(value, 0); } catch { return String(value); }
}
