import { pdf } from '@react-pdf/renderer';
import ResumePdf from './ResumePdf';
import { buildResumeFilename, type ResumeDocument } from '../types';

/**
 * AETHER Resume Builder — PDF export (spec §21–§22).
 *
 * The export is a genuine text PDF generated by @react-pdf/renderer: the text is
 * selectable and extractable (no html2canvas screenshot, no PNG-wrapped PDF).
 * `buildResumeBlob` is shared by the preview and the download button so both
 * render the exact same document.
 */

export async function buildResumeBlob(doc: ResumeDocument, template: string): Promise<Blob> {
  return pdf(<ResumePdf doc={doc} template={template} />).toBlob();
}

export interface DownloadResult {
  filename: string;
  bytes: number;
}

/** Generate and trigger the download with a dynamic filename (spec §22). */
export async function downloadResumePdf(doc: ResumeDocument, template: string): Promise<DownloadResult> {
  const blob = await buildResumeBlob(doc, template);
  const filename = buildResumeFilename(doc.name, doc.title);
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  // Give the browser a moment to start the download before revoking.
  setTimeout(() => URL.revokeObjectURL(url), 4000);
  return { filename, bytes: blob.size };
}
