import { Reveal, SectionHeading } from './Reveal';

const STEPS = [
  { n: '01', title: 'Choose Target Role', body: 'Pick the role you are preparing for. Requirements, roadmap and matching all scope to it.', tags: ['Role requirements', 'Readiness baseline'] },
  { n: '02', title: 'Build Your Evidence', body: 'Assessments, coding problems, mock interviews and resume analysis all write to the same skill profile.', tags: ['Aptitude', 'Coding', 'Interview', 'Resume'] },
  { n: '03', title: 'Close Skill Gaps', body: 'The learning roadmap is generated from the requirements your evidence does not yet cover.', tags: ['Learning roadmap', 'Targeted practice'] },
  { n: '04', title: 'Match Opportunities', body: 'Compare real job descriptions against your profile and shortlist on evidence, not keywords.', tags: ['Job Fit', 'Jobs'] },
  { n: '05', title: 'Track Readiness', body: 'Watch readiness, analytics and streak move as your stored evidence grows.', tags: ['Dashboard', 'Analytics', 'Streak'] },
];

const TRUST = [
  'Deterministic Scoring',
  'Evidence Provenance',
  'Role-Aware Progress',
  'ATS-Safe Resume',
  'AST-Based Coding Analysis',
  'Real Job Data',
  'Explainable Recommendations',
];

export function WorkflowSection() {
  return (
    <section id="how-it-works" className="scroll-mt-20 border-t border-slate-100 bg-[#F8FAFC] py-16 sm:py-24">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 xl:px-8">
        <SectionHeading
          eyebrow="How it works"
          title="A Preparation Loop, Not a Checklist."
          lede="Five stages that feed each other — every stage produces evidence the next one consumes."
        />

        <ol className="mt-12 grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-5">
          {STEPS.map((s, i) => (
            <Reveal key={s.n} delay={i * 0.06} as="li">
              <div className="flex h-full flex-col rounded-2xl border border-slate-200 bg-white p-5 transition-all duration-300 hover:-translate-y-0.5 hover:border-indigo-300 hover:shadow-[0_18px_44px_-26px_rgba(79,70,229,0.5)]">
                <span className="text-2xl font-black tabular-nums leading-none text-indigo-200">{s.n}</span>
                <h3 className="mt-2.5 text-[14.5px] font-bold text-slate-900">{s.title}</h3>
                <p className="mt-2 flex-1 text-[13px] leading-relaxed text-slate-600">{s.body}</p>
                <div className="mt-3 flex flex-wrap gap-1.5">
                  {s.tags.map(t => (
                    <span key={t} className="rounded-full bg-slate-100 px-2 py-0.5 text-[10.5px] font-medium text-slate-600">{t}</span>
                  ))}
                </div>
              </div>
            </Reveal>
          ))}
        </ol>
      </div>
    </section>
  );
}

export function TrustSection() {
  return (
    <section className="border-t border-slate-100 bg-white py-16 sm:py-20">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 xl:px-8">
        <Reveal className="mx-auto max-w-3xl text-center">
          <p className="mb-3 text-[11px] font-bold uppercase tracking-[0.18em] text-indigo-500">Built around the journey</p>
          <h2 className="text-2xl font-black tracking-tight text-slate-900 sm:text-3xl">
            Engineered for Explainability
          </h2>
          <p className="mt-3 text-base leading-relaxed text-slate-600">
            Progress you can trace — real assessment history, real resume analysis, real learning
            progress and actual stored skill evidence. No graph on this platform is generated by AI.
          </p>
        </Reveal>

        <Reveal delay={0.06}>
          <div className="mt-10 flex flex-wrap justify-center gap-2.5">
            {TRUST.map(t => (
              <span key={t} className="rounded-full border border-slate-200 bg-white px-3.5 py-1.5 text-[12.5px] font-semibold text-slate-700 transition-colors hover:border-indigo-300 hover:text-indigo-700">
                {t}
              </span>
            ))}
          </div>
          <div className="mt-8 flex flex-wrap justify-center gap-2">
            {['Aptitude', 'Technical', 'Coding', 'Interview', 'Resume', 'Career Learning', 'Career Intelligence', 'Jobs', 'Analytics'].map(m => (
              <span key={m} className="rounded-md bg-slate-100 px-2.5 py-1 text-[11px] font-medium text-slate-600">{m}</span>
            ))}
          </div>
        </Reveal>
      </div>
    </section>
  );
}