import { SeedProblem } from './problems.part1';

export const PROBLEMS_PART2: SeedProblem[] = [
  {
    title: 'Linked List Cycle',
    slug: 'linked-list-cycle',
    description:
      'A linked list is given as a JSON array of [value, nextIndex] pairs, where nextIndex = -1 means the node has no next node. Starting from node 0 and following next pointers, return true if the traversal never terminates (a cycle exists), false otherwise.',
    difficulty: 'Easy',
    category: 'Linked Lists',
    tags: ['Linked List', 'Two Pointers'],
    companies: ['Amazon', 'Microsoft'],
    examples: [
      { input: 'head = [[1,-1],[2,-1],[3,-1]]', output: 'false' },
      { input: 'head = [[1,1],[2,0]]', output: 'true', explanation: 'Node 0 points to node 1, node 1 points back to node 0 — infinite loop.' },
    ],
    constraints: ['0 <= nodes <= 10^4', 'Each node is [value, nextIndex]; nextIndex = -1 means no next node.'],
    sampleTests: [
      { input: '[[1,-1],[2,-1],[3,-1]]', expectedOutput: 'false' },
      { input: '[[1,1],[2,0]]', expectedOutput: 'true' },
    ],
    hiddenTests: [
      { input: '[[1,-1],[2,-1],[3,-1]]', expectedOutput: 'false' },
      { input: '[[5,-1]]', expectedOutput: 'false' },
      { input: '[[1,2],[2,2],[3,0]]', expectedOutput: 'true' },
    ],
    functionName: 'hasCycle',
    params: ['head'],
    javaSignature: { returnType: 'boolean', paramTypes: ['int[]'] },
    cppSignature: { returnType: 'bool', paramTypes: ['vector<int>'] },
    knownApproaches: [
      {
        name: 'Hash Set of Seen Nodes',
        approachId: 'HASHING',
        timeComplexity: 'O(n)',
        spaceComplexity: 'O(n)',
        outline: 'Track visited values; a repeat implies a cycle in this encoding.',
        optimal: false,
      },
      {
        name: 'Floyd Tortoise & Hare',
        approachId: 'TWO_POINTER',
        timeComplexity: 'O(n)',
        spaceComplexity: 'O(1)',
        outline: 'Advance slow by 1 and fast by 2; they meet iff there is a cycle.',
        optimal: true,
      },
    ],
    expectedTimeComplexity: 'O(n)',
    expectedSpaceComplexity: 'O(1)',
    points: 10,
    hints: [
      'In a cycle, following next pointers eventually revisits a node.',
      'Store visited node indices in a hash set while walking.',
      'If you ever see an index twice — or hit nextIndex = -1 — you have your answer.',
    ],
    solutionOutline: 'Walk nodes following next pointers, tracking visited indices in a set; a revisit means a cycle. O(n)/O(n).',
  },
  {
    title: 'Merge Intervals',
    slug: 'merge-intervals',
    description:
      'Given an array of intervals where intervals[i] = [start, end], merge all overlapping intervals and return an array of the non-overlapping intervals that cover all the input intervals.',
    difficulty: 'Medium',
    category: 'Sorting',
    tags: ['Array', 'Sorting'],
    companies: ['Google', 'Facebook', 'Bloomberg'],
    examples: [
      { input: 'intervals = [[1,3],[2,6],[8,10]]', output: '[[1,6],[8,10]]' },
      { input: 'intervals = [[1,4],[4,5]]', output: '[[1,5]]' },
    ],
    constraints: ['1 <= intervals.length <= 10^4', 'intervals[i].length == 2', 'start <= end'],
    sampleTests: [
      { input: '[[1,3],[2,6],[8,10]]', expectedOutput: '[[1,6],[8,10]]' },
      { input: '[[1,4],[4,5]]', expectedOutput: '[[1,5]]' },
    ],
    hiddenTests: [
      { input: '[[1,4],[0,4]]', expectedOutput: '[[0,4]]' },
      { input: '[[1,4],[2,3]]', expectedOutput: '[[1,4]]' },
      { input: '[[5,6]]', expectedOutput: '[[5,6]]' },
    ],
    functionName: 'merge',
    params: ['intervals'],
    javaSignature: { returnType: 'int[][]', paramTypes: ['int[][]'] },
    cppSignature: { returnType: 'vector<vector<int>>', paramTypes: ['vector<vector<int>>&'] },
    knownApproaches: [
      {
        name: 'Sort and Merge',
        approachId: 'SORTING_BASED',
        timeComplexity: 'O(n log n)',
        spaceComplexity: 'O(n)',
        outline: 'Sort by start; extend the last interval while the current one overlaps.',
        optimal: true,
      },
    ],
    expectedTimeComplexity: 'O(n log n)',
    expectedSpaceComplexity: 'O(n)',
    points: 15,
    hints: [
      'After sorting by start, overlapping intervals are adjacent.',
      'Keep a result list; compare each interval with the last one in the result.',
      'If current.start <= last.end, merge by extending last.end = max(last.end, current.end).',
    ],
    solutionOutline: 'Sort by start then linear merge pass. O(n log n)/O(n).',
  },
  {
    title: 'Kth Largest Element',
    slug: 'kth-largest-element',
    description:
      'Given an integer array nums and an integer k, return the kth largest element in the array. Note that it is the kth largest element in sorted order, not the kth distinct element.',
    difficulty: 'Medium',
    category: 'Heaps',
    tags: ['Array', 'Heap', 'Sorting'],
    companies: ['Facebook', 'Amazon', 'Google'],
    examples: [
      { input: 'nums = [3,2,1,5,6,4], k = 2', output: '5' },
      { input: 'nums = [3,2,3,1,2,4,5,5,6], k = 4', output: '4' },
    ],
    constraints: ['1 <= k <= nums.length <= 10^5'],
    sampleTests: [
      { input: '[3,2,1,5,6,4]\n2', expectedOutput: '5' },
      { input: '[3,2,3,1,2,4,5,5,6]\n4', expectedOutput: '4' },
    ],
    hiddenTests: [
      { input: '[1]\n1', expectedOutput: '1' },
      { input: '[7,7,7]\n2', expectedOutput: '7' },
      { input: '[2,1]\n2', expectedOutput: '1' },
    ],
    functionName: 'findKthLargest',
    params: ['nums', 'k'],
    javaSignature: { returnType: 'int', paramTypes: ['int[]', 'int'] },
    cppSignature: { returnType: 'int', paramTypes: ['vector<int>&', 'int'] },
    knownApproaches: [
      {
        name: 'Sort and Index',
        approachId: 'SORTING_BASED',
        timeComplexity: 'O(n log n)',
        spaceComplexity: 'O(1)',
        outline: 'Sort descending and take index k-1.',
        optimal: false,
      },
      {
        name: 'Min-Heap of Size k',
        approachId: 'HEAP',
        timeComplexity: 'O(n log k)',
        spaceComplexity: 'O(k)',
        outline: 'Maintain a min-heap of the k largest seen so far.',
        optimal: true,
      },
    ],
    expectedTimeComplexity: 'O(n log k)',
    expectedSpaceComplexity: 'O(k)',
    points: 15,
    hints: [
      'You only need the top k elements, not a full sort.',
      'A min-heap of size k keeps the k largest; the root is the answer.',
      'Alternative: quickselect gives average O(n).',
    ],
    solutionOutline: 'Min-heap of size k over the stream of values. O(n log k)/O(k).',
  },
  {
    title: 'Maximum Depth of Binary Tree',
    slug: 'maximum-depth-of-binary-tree',
    description:
      'Given the root of a binary tree represented as a level-order array where null nodes are encoded as the string "null", return its maximum depth. The depth is the number of nodes along the longest path from the root node down to the farthest leaf node.',
    difficulty: 'Easy',
    category: 'Trees',
    tags: ['Tree', 'Recursion', 'BFS'],
    companies: ['Amazon', 'Google'],
    examples: [
      { input: 'root = [3,9,20,"null","null",15,7]', output: '3' },
      { input: 'root = [1,"null",2]', output: '2' },
    ],
    constraints: ['0 <= nodes <= 10^4', '-100 <= values <= 100'],
    sampleTests: [
      { input: '[3,9,20,"null","null",15,7]', expectedOutput: '3' },
      { input: '[1,"null",2]', expectedOutput: '2' },
    ],
    hiddenTests: [
      { input: '[]', expectedOutput: '0' },
      { input: '[0]', expectedOutput: '1' },
      { input: '[1,2,3,4,5,"null","null",6]', expectedOutput: '4' },
    ],
    functionName: 'maxDepth',
    params: ['root'],
    javaSignature: { returnType: 'int', paramTypes: ['Object[]'] },
    cppSignature: { returnType: 'int', paramTypes: ['vector<string>'] },
    knownApproaches: [
      {
        name: 'Recursive DFS',
        approachId: 'DFS',
        timeComplexity: 'O(n)',
        spaceComplexity: 'O(h)',
        outline: 'depth(node) = 1 + max(depth(left), depth(right)).',
        optimal: true,
      },
      {
        name: 'BFS Level Count',
        approachId: 'BFS',
        timeComplexity: 'O(n)',
        spaceComplexity: 'O(w)',
        outline: 'Count levels while traversing level by level with a queue.',
        optimal: true,
      },
    ],
    expectedTimeComplexity: 'O(n)',
    expectedSpaceComplexity: 'O(n)',
    points: 10,
    hints: [
      'The depth of a tree is 1 + the deeper of its two subtrees.',
      'Think recursively: base case is a null node with depth 0.',
      'Alternatively, count levels with a BFS queue.',
    ],
    solutionOutline: 'Recursive depth function over level-order parsed tree. O(n)/O(h).',
  },
  {
    title: 'Number of Islands',
    slug: 'number-of-islands',
    description:
      'Given an m x n binary grid where 1 is land and 0 is water, return the number of islands. An island is surrounded by water and formed by connecting adjacent lands horizontally or vertically (not diagonally).\n\nInput format: first line is the grid as JSON, e.g. [[1,1,0],[1,0,0],[0,0,1]].',
    difficulty: 'Medium',
    category: 'Graphs',
    tags: ['Matrix', 'DFS', 'BFS', 'Union Find'],
    companies: ['Amazon', 'Microsoft', 'Google'],
    examples: [
      { input: 'grid = [[1,1,0],[1,0,0],[0,0,1]]', output: '2' },
      { input: 'grid = [[1,1],[1,1]]', output: '1' },
    ],
    constraints: ['1 <= m, n <= 300'],
    sampleTests: [
      { input: '[[1,1,0],[1,0,0],[0,0,1]]', expectedOutput: '2' },
      { input: '[[1,1],[1,1]]', expectedOutput: '1' },
    ],
    hiddenTests: [
      { input: '[[0,0],[0,0]]', expectedOutput: '0' },
      { input: '[[1]]', expectedOutput: '1' },
      { input: '[[1,0,1,0,1]]', expectedOutput: '3' },
    ],
    functionName: 'numIslands',
    params: ['grid'],
    javaSignature: { returnType: 'int', paramTypes: ['int[][]'] },
    cppSignature: { returnType: 'int', paramTypes: ['vector<vector<int>>&'] },
    knownApproaches: [
      {
        name: 'DFS Flood Fill',
        approachId: 'DFS',
        timeComplexity: 'O(m*n)',
        spaceComplexity: 'O(m*n)',
        outline: 'For each unvisited land cell, flood-fill the entire island.',
        optimal: true,
      },
      {
        name: 'BFS Flood Fill',
        approachId: 'BFS',
        timeComplexity: 'O(m*n)',
        spaceComplexity: 'O(min(m,n))',
        outline: 'Same as DFS but with a queue.',
        optimal: true,
      },
      {
        name: 'Union-Find',
        approachId: 'UNION_FIND',
        timeComplexity: 'O(m*n * α)',
        spaceComplexity: 'O(m*n)',
        outline: 'Union adjacent land cells; count distinct roots.',
        optimal: false,
      },
    ],
    expectedTimeComplexity: 'O(m*n)',
    expectedSpaceComplexity: 'O(m*n)',
    points: 20,
    hints: [
      'Scan every cell; when you find unvisited land, that is a new island.',
      'Sink the whole island (mark visited) before moving on.',
      'Flood fill via DFS recursion or a BFS queue.',
    ],
    solutionOutline: 'Grid scan + flood fill marking visited cells. O(m*n).',
  },
  {
    title: 'Course Schedule',
    slug: 'course-schedule',
    description:
      'There are numCourses courses labeled 0 to numCourses-1 and a list prerequisites where prerequisites[i] = [a, b] means you must take course b before course a. Return true if you can finish all courses (no cycle in the prerequisite graph).\n\nInput: first line numCourses, second line prerequisites as JSON.',
    difficulty: 'Medium',
    category: 'Graphs',
    tags: ['Graph', 'Topological Sort', 'DFS'],
    companies: ['Google', 'Amazon', 'Uber'],
    examples: [
      { input: 'numCourses = 2, prerequisites = [[1,0]]', output: 'true' },
      { input: 'numCourses = 2, prerequisites = [[1,0],[0,1]]', output: 'false' },
    ],
    constraints: ['1 <= numCourses <= 2000', '0 <= prerequisites.length <= 5000'],
    sampleTests: [
      { input: '2\n[[1,0]]', expectedOutput: 'true' },
      { input: '2\n[[1,0],[0,1]]', expectedOutput: 'false' },
    ],
    hiddenTests: [
      { input: '1\n[]', expectedOutput: 'true' },
      { input: '3\n[[0,1],[1,2],[2,0]]', expectedOutput: 'false' },
      { input: '4\n[[1,0],[2,1],[3,2]]', expectedOutput: 'true' },
    ],
    functionName: 'canFinish',
    params: ['numCourses', 'prerequisites'],
    javaSignature: { returnType: 'boolean', paramTypes: ['int', 'int[][]'] },
    cppSignature: { returnType: 'bool', paramTypes: ['int', 'vector<vector<int>>&'] },
    knownApproaches: [
      {
        name: 'Kahn Topological Sort (BFS)',
        approachId: 'BFS',
        timeComplexity: 'O(V + E)',
        spaceComplexity: 'O(V + E)',
        outline: 'Compute in-degrees, repeatedly take zero in-degree nodes.',
        optimal: true,
      },
      {
        name: 'DFS Cycle Detection',
        approachId: 'DFS',
        timeComplexity: 'O(V + E)',
        spaceComplexity: 'O(V + E)',
        outline: 'Color nodes white/gray/black; a gray hit means a cycle.',
        optimal: true,
      },
    ],
    expectedTimeComplexity: 'O(V + E)',
    expectedSpaceComplexity: 'O(V + E)',
    points: 20,
    hints: [
      'Model courses as a directed graph: edge b → a for each [a, b] prerequisite.',
      'You can finish all courses iff the graph has no directed cycle.',
      'Kahn algorithm with in-degree counting, or DFS with a recursion stack.',
    ],
    solutionOutline: 'Build adjacency + in-degree, BFS topological sort, compare processed count. O(V+E).',
  },
  {
    title: 'Coin Change',
    slug: 'coin-change',
    description:
      'You are given coins of different denominations and a total amount of money. Return the fewest coins needed to make up that amount, or -1 if it cannot be composed. You may use each coin an unlimited number of times.',
    difficulty: 'Medium',
    category: 'Dynamic Programming',
    tags: ['Dynamic Programming', 'BFS'],
    companies: ['Amazon', 'Microsoft', 'Google'],
    examples: [
      { input: 'coins = [1,2,5], amount = 11', output: '3', explanation: '5 + 5 + 1.' },
      { input: 'coins = [2], amount = 3', output: '-1' },
    ],
    constraints: ['1 <= coins.length <= 12', '0 <= amount <= 10^4'],
    sampleTests: [
      { input: '[1,2,5]\n11', expectedOutput: '3' },
      { input: '[2]\n3', expectedOutput: '-1' },
    ],
    hiddenTests: [
      { input: '[1]\n0', expectedOutput: '0' },
      { input: '[1,5,6,9]\n11', expectedOutput: '2' },
      { input: '[186,419,83,408]\n6249', expectedOutput: '20' },
    ],
    functionName: 'coinChange',
    params: ['coins', 'amount'],
    javaSignature: { returnType: 'int', paramTypes: ['int[]', 'int'] },
    cppSignature: { returnType: 'int', paramTypes: ['vector<int>&', 'int'] },
    knownApproaches: [
      {
        name: 'Greedy (incorrect in general)',
        approachId: 'GREEDY',
        timeComplexity: 'O(n log n)',
        spaceComplexity: 'O(1)',
        outline: 'Repeatedly take the largest coin — fails for cases like [1,5,6,9], amount 11.',
        optimal: false,
      },
      {
        name: 'Bottom-Up DP',
        approachId: 'TABULATION',
        timeComplexity: 'O(amount * n)',
        spaceComplexity: 'O(amount)',
        outline: 'dp[a] = min over coins of dp[a-coin] + 1.',
        optimal: true,
      },
    ],
    expectedTimeComplexity: 'O(amount * n)',
    expectedSpaceComplexity: 'O(amount)',
    points: 20,
    hints: [
      'Think about the smallest number of coins to make each amount from 0 up to the target.',
      'dp[a] = 1 + min(dp[a - coin]) over all coins <= a.',
      'Initialize dp[0] = 0 and everything else as infinity.',
    ],
    solutionOutline: 'Bottom-up DP over amounts with per-coin transitions. O(amount·n)/O(amount).',
  },
  {
    title: 'House Robber',
    slug: 'house-robber',
    description:
      'You are a robber planning to rob houses along a street. Each house has a certain amount of money; adjacent houses have connected alarms, so you cannot rob two adjacent houses. Return the maximum amount you can rob tonight.',
    difficulty: 'Medium',
    category: 'Dynamic Programming',
    tags: ['Dynamic Programming', 'Array'],
    companies: ['Amazon', 'Google', 'Visa'],
    examples: [
      { input: 'nums = [1,2,3,1]', output: '4', explanation: 'Rob house 0 and house 2.' },
      { input: 'nums = [2,7,9,3,1]', output: '12' },
    ],
    constraints: ['1 <= nums.length <= 100', '0 <= nums[i] <= 400'],
    sampleTests: [
      { input: '[1,2,3,1]', expectedOutput: '4' },
      { input: '[2,7,9,3,1]', expectedOutput: '12' },
    ],
    hiddenTests: [
      { input: '[2,1,1,2]', expectedOutput: '4' },
      { input: '[5]', expectedOutput: '5' },
      { input: '[1,3,1,3,100]', expectedOutput: '103' },
    ],
    functionName: 'rob',
    params: ['nums'],
    javaSignature: { returnType: 'int', paramTypes: ['int[]'] },
    cppSignature: { returnType: 'int', paramTypes: ['vector<int>&'] },
    knownApproaches: [
      {
        name: 'DP with Rolling Variables',
        approachId: 'DYNAMIC_PROGRAMMING',
        timeComplexity: 'O(n)',
        spaceComplexity: 'O(1)',
        outline: 'take = skip + nums[i]; skip = max(skip, take) — track two values.',
        optimal: true,
      },
      {
        name: 'Brute Force Recursion',
        approachId: 'RECURSION',
        timeComplexity: 'O(2^n)',
        spaceComplexity: 'O(n)',
        outline: 'Rob or skip each house recursively.',
        optimal: false,
      },
    ],
    expectedTimeComplexity: 'O(n)',
    expectedSpaceComplexity: 'O(1)',
    points: 15,
    hints: [
      'At each house choose: rob it (plus best up to i-2) or skip it (best up to i-1).',
      'best(i) = max(best(i-1), best(i-2) + nums[i]).',
      'Two variables are enough — no array needed.',
    ],
    solutionOutline: 'Rolling DP over rob/skip values. O(n)/O(1).',
  },
  {
    title: 'Combination Sum',
    slug: 'combination-sum',
    description:
      'Given an array of distinct integers candidates and a target integer, return all unique combinations of candidates that sum to target. The same number may be chosen an unlimited number of times. Return combinations in sorted order as JSON.',
    difficulty: 'Medium',
    category: 'Backtracking',
    tags: ['Array', 'Backtracking'],
    companies: ['Amazon', 'Facebook', 'Bloomberg'],
    examples: [
      { input: 'candidates = [2,3,6,7], target = 7', output: '[[2,2,3],[7]]' },
      { input: 'candidates = [2,3,5], target = 8', output: '[[2,2,2,2],[2,3,3],[3,5]]' },
    ],
    constraints: ['1 <= candidates.length <= 30', 'All elements distinct', '2 <= target <= 40'],
    sampleTests: [
      { input: '[2,3,6,7]\n7', expectedOutput: '[[2,2,3],[7]]' },
      { input: '[2,3,5]\n8', expectedOutput: '[[2,2,2,2],[2,3,3],[3,5]]' },
    ],
    hiddenTests: [
      { input: '[2]\n1', expectedOutput: '[]' },
      { input: '[2,3]\n7', expectedOutput: '[[2,2,3]]' },
    ],
    functionName: 'combinationSum',
    params: ['candidates', 'target'],
    javaSignature: { returnType: 'List<List<Integer>>', paramTypes: ['int[]', 'int'] },
    cppSignature: { returnType: 'vector<vector<int>>', paramTypes: ['vector<int>&', 'int'] },
    knownApproaches: [
      {
        name: 'Backtracking',
        approachId: 'BACKTRACKING',
        timeComplexity: 'O(n^(T/M))',
        spaceComplexity: 'O(T/M)',
        outline: 'Explore candidates in order, allowing reuse; backtrack when the remaining target is negative.',
        optimal: true,
      },
    ],
    expectedTimeComplexity: 'O(n^(T/M))',
    expectedSpaceComplexity: 'O(T/M)',
    points: 20,
    hints: [
      'Process candidates in a fixed order to avoid duplicate combinations.',
      'On each recursion you may reuse the current candidate.',
      'When remaining becomes 0, record the current combination; when negative, backtrack.',
    ],
    solutionOutline: 'DFS backtracking with index-bound to keep combinations sorted and unique.',
  },
  {
    title: 'Valid Anagram — Frequency Map',
    slug: 'valid-anagram-frequency-map',
    description:
      'Variant of Valid Anagram that must use a hash map. Given two strings s and t, return true if t is an anagram of s using map-based counting (useful for practicing AST hash-detection).',
    difficulty: 'Easy',
    category: 'Hashing',
    tags: ['String', 'Hash Table'],
    companies: ['Google'],
    examples: [
      { input: 's = "listen", t = "silent"', output: 'true' },
      { input: 's = "hello", t = "world"', output: 'false' },
    ],
    constraints: ['1 <= s.length, t.length <= 5*10^4'],
    sampleTests: [
      { input: 'listen\nsilent', expectedOutput: 'true' },
      { input: 'hello\nworld', expectedOutput: 'false' },
    ],
    hiddenTests: [
      { input: 'aab\naba', expectedOutput: 'true' },
      { input: 'x\nxx', expectedOutput: 'false' },
    ],
    functionName: 'isAnagramMap',
    params: ['s', 't'],
    javaSignature: { returnType: 'boolean', paramTypes: ['String', 'String'] },
    cppSignature: { returnType: 'bool', paramTypes: ['string', 'string'] },
    knownApproaches: [
      {
        name: 'Hash Map Counting',
        approachId: 'HASHING',
        timeComplexity: 'O(n)',
        spaceComplexity: 'O(k)',
        outline: 'Count chars of s in a map, decrement with t, verify all zero.',
        optimal: true,
      },
    ],
    expectedTimeComplexity: 'O(n)',
    expectedSpaceComplexity: 'O(k)',
    points: 10,
    hints: [
      'One map can do both increments and decrements.',
      'After processing both strings every counter must be zero.',
      'Early exit if lengths differ.',
    ],
    solutionOutline: 'Map-based frequency counting with early length check. O(n)/O(k).',
  },
];
