import { apiService } from './api';

/**
 * AETHER Career Learning — database-backed lesson client (spec §28–§59).
 *
 * Every field below is served from MongoDB by the backend; nothing on the
 * lesson page is hardcoded in JSX and nothing numeric is generated by AI.
 */

export type TopicState = 'NOT_STARTED' | 'IN_PROGRESS' | 'COMPLETED' | 'REVIEW_NEEDED';
export type TopicLevel = 'beginner' | 'intermediate' | 'advanced';

export type BlockType =
  | 'heading' | 'paragraph' | 'list' | 'code' | 'tip' | 'warning'
  | 'note' | 'table' | 'steps' | 'compare';

export interface TopicBlock {
  type: BlockType;
  content?: string;
  items?: string[];
  columns?: string[];
  rows?: string[][];
  leftTitle?: string;
  rightTitle?: string;
  leftItems?: string[];
  rightItems?: string[];
  language?: string;
  code?: string;
  output?: string;
  caption?: string;
}

export interface TopicExample {
  title: string; kind: string; explanation: string; language: string; code: string; output?: string;
}

export interface TopicCommonMistake {
  title: string; wrong: string; wrongLanguage?: string; why: string; fix?: string; fixLanguage?: string;
}

export interface TopicInterviewTip { question: string; answer: string; difficulty?: TopicLevel }

export interface TopicPractice {
  level: 'EASY' | 'MEDIUM' | 'CHALLENGE';
  prompt: string; hint?: string; expectedKeywords?: string[];
}

export interface TopicQuizQuestion {
  id: string; question: string; options: string[]; difficulty: TopicLevel; topicTag: string;
}

export interface TopicResource {
  title: string; url: string; provider: string;
  type: 'DOCUMENTATION' | 'ARTICLE' | 'VIDEO' | 'PRACTICE' | 'BOOK';
}

export interface TopicNavItem {
  slug: string; title: string; group: string; level: TopicLevel; estimatedMinutes: number;
  order: number; state: TopicState; bookmarked: boolean; locked: boolean;
  hasQuiz: boolean; hasVideo: boolean;
}

export interface TopicLink {
  slug: string; title: string; shortDescription: string; level: TopicLevel; estimatedMinutes?: number;
}

export interface TopicVideo {
  youtubeVideoId: string; title: string; channelTitle: string; thumbnail: string;
  duration: string; durationSeconds: number | null;
  viewCount: number | null; likeCount: number | null;
  publishedAt: string | null; rankingScore: number; rankingReasons: string[];
  fetchedAt: string; label: string;
}

export interface TopicPage {
  topic: {
    id: string; slug: string; title: string; shortDescription: string; description: string;
    whyItMatters: string; interviewRelevance: string; group: string; order: number;
    level: TopicLevel; estimatedMinutes: number; contentVersion: number; source: string;
    reviewedBy?: string; publishedAt?: string; updatedAt?: string;
    skillSlugs: string[]; roleSlugs: string[]; courseSlugs: string[];
    prerequisites: string[]; optionalPrerequisites: string[];
    learningObjectives: string[]; sections: TopicBlock[]; examples: TopicExample[];
    commonMistakes: TopicCommonMistake[]; interviewTips: TopicInterviewTip[];
    practice: TopicPractice[]; quiz: TopicQuizQuestion[]; resources: TopicResource[];
    nextTopicSlugs: string[]; relatedTopicSlugs: string[];
  };
  progress: {
    state: TopicState; bookmarked: boolean; notes: string; lastBlockIndex: number;
    bestQuizScore: number | null; attempts: number;
  };
  prerequisites: Array<{ slug: string; title: string; state: TopicState; optional: boolean; estimatedMinutes: number }>;
  locked: boolean;
  nextTopics: TopicLink[];
  relatedTopics: TopicLink[];
  videos: TopicVideo[];
  videoStatus: {
    configured: boolean; available: boolean; credentialRequest: string | null; lastFetchedAt: string | null;
  };
  stats: { totalBlocks: number; exampleCount: number; practiceCount: number; quizCount: number };
}

export interface QuizQuestionView { id: string; question: string; options: string[]; difficulty: TopicLevel; topicTag: string }

export interface QuizResult {
  score: number; correct: number; total: number;
  results: Array<{ id: string; correct: boolean; correctIndex: number; explanation: string; difficulty: string; topicTag: string }>;
  weakTags: string[];
  recommendations: Array<{ slug: string | null; title: string; reason: string }>;
  stateAfter: TopicState;
}

export interface ContinueLearningItem {
  topicSlug: string; title: string; group: string; estimatedMinutes: number;
  state: TopicState; progressPercent: number; bestQuizScore: number | null; updatedAt: string;
}

export interface TopicRecommendation {
  slug: string; title: string; shortDescription: string; level: TopicLevel;
  estimatedMinutes: number; group: string; reason: string;
}

export interface AskMode {
  mode: 'EXPLAIN_SIMPLY' | 'ANOTHER_EXAMPLE' | 'EXPLAIN_CODE' | 'QUIZ_ME' | 'INTERVIEW_QUESTION' | 'COMPARE';
}

/** Admin CMS shapes (spec §39) — mirrors the /api/admin/careers/topics payload. */
export type TopicStatus = 'draft' | 'review' | 'published' | 'archived';

export interface AdminTopicSummary {
  _id: string;
  slug: string;
  title: string;
  group: string;
  level: TopicLevel | string;
  estimatedMinutes: number;
  status: TopicStatus;
  contentVersion: number;
  source: string;
  order: number;
  updatedAt: string;
  counts: { blocks: number; examples: number; quiz: number; prerequisites: number; nextTopics: number };
}

export interface AdminTopicDetail {
  _id: string;
  slug: string;
  title: string;
  shortDescription: string;
  description: string;
  whyItMatters: string;
  interviewRelevance: string;
  group: string;
  order: number;
  level: TopicLevel;
  estimatedMinutes: number;
  status: TopicStatus;
  contentVersion: number;
  source: string;
  reviewedBy?: string;
  publishedAt?: string | null;
  learningObjectives: string[];
  prerequisites: string[];
  optionalPrerequisites: string[];
  nextTopicSlugs: string[];
  relatedTopicSlugs: string[];
  skillSlugs: string[];
  roleSlugs: string[];
  sections: TopicBlock[];
  examples: TopicExample[];
  commonMistakes: TopicCommonMistake[];
  interviewTips: TopicInterviewTip[];
  practice: TopicPractice[];
  quiz: Array<{ id: string; question: string; options: string[]; correctIndex: number; explanation: string; difficulty: TopicLevel; topicTag: string }>;
  resources: TopicResource[];
  updatedAt?: string;
}

export interface AdminTopicVideo {
  _id: string;
  topicSlug: string;
  youtubeVideoId: string;
  title: string;
  channelTitle: string;
  duration: string;
  viewCount: number | null;
  likeCount: number | null;
  relevanceScore: number;
  rankingScore: number;
  rankingReasons: string[];
  fetchedAt: string;
  active: boolean;
  inactiveReason?: string;
}

function unwrap<T>(res: { success?: boolean; data?: T; error?: string; message?: string }): T {
  if (res && res.success === false) throw new Error(res.error || res.message || 'Request failed');
  return res.data as T;
}

export interface AskAnswer {
  answer: string;
  points?: string[];
  example?: string | null;
  groundedIn?: string;
  aiAvailable?: boolean;
  cached?: boolean;
  mode?: string;
}

function request<T>(promise: Promise<{ success?: boolean; data?: T; error?: string; message?: string }>): Promise<T> {
  return promise.then(unwrap<T>);
}

const learningTopicsService = {
  // ── Learner ────────────────────────────────────────────────────────────────
  listTopics(params: { group?: string; role?: string } = {}) {
    return request<{ topics: TopicNavItem[]; groups: string[] }>(
      apiService.get('/careers/topics', params),
    );
  },

  getTopic(slug: string) {
    return request<TopicPage>(apiService.get(`/careers/topics/${slug}`));
  },

  setState(slug: string, state: TopicState) {
    return request<{ topicSlug: string; state: TopicState; bookmarked: boolean }>(
      apiService.put(`/careers/topics/${slug}/progress`, { state }),
    );
  },

  toggleBookmark(slug: string, bookmarked?: boolean) {
    return request<{ topicSlug: string; bookmarked: boolean; state: TopicState }>(
      apiService.post(`/careers/topics/${slug}/bookmark`, bookmarked === undefined ? {} : { bookmarked }),
    );
  },

  saveNotes(slug: string, notes: string, lastBlockIndex?: number) {
    return request<{ notes: string; lastBlockIndex: number; state: TopicState; updatedAt: string }>(
      apiService.put(`/careers/topics/${slug}/notes`, { notes, lastBlockIndex }),
    );
  },

  getQuiz(slug: string) {
    return request<{ questions: QuizQuestionView[] }>(apiService.get(`/careers/topics/${slug}/quiz`));
  },

  submitQuiz(slug: string, answers: number[]) {
    return request<QuizResult>(apiService.post(`/careers/topics/${slug}/quiz`, { answers }));
  },

  /** Supplementary AI tutor — the lesson works fully without it (§55–§56). */
  ask(slug: string, question: string) {
    return request<AskAnswer>(apiService.post(`/careers/topics/${slug}/ask`, { question }, { timeout: 60000 }));
  },

  continueLearning() {
    return request<{ items: ContinueLearningItem[]; emptyState: string | null }>(
      apiService.get('/careers/me/continue-learning'),
    );
  },

  recommendations() {
    return request<{
      recommendations: TopicRecommendation[];
      evidence: { reviewNeeded: number; completed: number; inProgress: number };
      emptyState: string | null;
    }>(apiService.get('/careers/me/topic-recommendations'));
  },

  /** Which database lesson covers a roadmap node (§52–§53). */
  resolveRoadmapNode(roleSlug: string, nodeId: string) {
    return request<{
      topicSlug: string | null; title?: string; shortDescription?: string; level?: TopicLevel;
      estimatedMinutes?: number; group?: string; matchedBy?: 'explicit-link' | 'skill-overlap';
    }>(apiService.get(`/careers/${roleSlug}/nodes/${nodeId}/lesson`));
  },

  // ── Admin CMS (§39) ────────────────────────────────────────────────────────
  adminListTopics(params: { status?: string } = {}) {
    return request<{
      topics: AdminTopicSummary[];
      videoRefreshConfigured: boolean;
      videoSelectionVersion: string;
      extensionOrder: string[];
    }>(apiService.get('/admin/careers/topics', params));
  },

  adminGetTopic(id: string) {
    return request<{ topic: AdminTopicDetail; videos: AdminTopicVideo[] }>(
      apiService.get(`/admin/careers/topics/${id}`),
    );
  },

  adminCreateTopic(payload: Record<string, unknown>) {
    return request<AdminTopicDetail>(apiService.post('/admin/careers/topics', payload));
  },

  adminUpdateTopic(id: string, payload: Record<string, unknown>) {
    return request<AdminTopicDetail>(apiService.put(`/admin/careers/topics/${id}`, payload));
  },

  adminPublishTopic(id: string) {
    return request<{ slug: string; status: TopicStatus }>(apiService.post(`/admin/careers/topics/${id}/publish`, {}));
  },

  adminUnpublishTopic(id: string) {
    return request<{ slug: string; status: TopicStatus }>(apiService.post(`/admin/careers/topics/${id}/unpublish`, {}));
  },

  adminArchiveTopic(id: string) {
    return request<{ slug: string; status: TopicStatus }>(apiService.post(`/admin/careers/topics/${id}/archive`, {}));
  },

  adminListVideos(params: { topic?: string } = {}) {
    return request<{
      videos: AdminTopicVideo[]; configured: boolean; selectionVersion: string; message: string | null;
    }>(apiService.get('/admin/careers/videos', params));
  },

  adminRefreshVideos(payload: { slug?: string; onlyStale?: boolean } = {}) {
    return request<{
      configured: boolean; selectionVersion: string; topicsProcessed: number;
      videosStored: number; videosDeactivated: number; quotaExceeded: boolean;
      message?: string; results: any[];
    }>(apiService.post('/admin/careers/videos/refresh', payload, { timeout: 120000 }));
  },

  adminValidateVideos() {
    return request<{ checked: number; deactivated: number; reason?: string }>(
      apiService.post('/admin/careers/videos/validate', {}, { timeout: 120000 }),
    );
  },
};

export default learningTopicsService;
